const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');

const html = read('brief/index.html');
const stagingHtml = read('brief-next/index.html');
const css = read('assets/brief/brief-demo.css');
const explainerCss = read('assets/brief/brief-demo-explainers.css');
const experienceCss = read('assets/brief/brief-demo-experience.css');
const docLinksCss = read('assets/brief/brief-demo-doc-links.css');
const dataJs = read('assets/brief/brief-demo-data.js');
const experienceJs = read('assets/brief/brief-demo-experience.js');
const mediaJs = read('assets/brief/brief-demo-media.js');
const appJs = read('assets/brief/brief-demo-app.js');
const explainersJs = read('assets/brief/brief-demo-explainers.js');
const docJs = read('assets/personal-os-doc.js');
const routes = JSON.parse(read('assets/cmx-routes.json'));

assert.match(html, /<html lang="en" data-theme="light">/);
assert.match(html, /<meta name="theme-color" content="#edf3f8"/i);
assert.match(html, /<meta name="robots" content="noindex, nofollow/);
assert.match(html, /<link rel="canonical" href="https:\/\/db\.cmxchat\.com\/brief\/"/);
assert.match(html, /script-src 'self' https:\/\/open\.spotify\.com/);
assert.match(html, /connect-src https:\/\/open\.spotify\.com/);
assert.match(html, /id="entryScenarioGrid"/);
assert.match(html, /id="entrySoundtrack" type="checkbox" checked/);
assert.match(html, /The final Open demo tap asks Spotify to play/);
assert.match(html, /Play the soundtrack when the demo opens/);
assert.doesNotMatch(html, /readOnEntry|read aloud/i);
assert.doesNotMatch(html, /Loading Spotify player\.\.\.|Preparing Spotify[^<]*\.\.\./);
assert.match(html, /data-view-panel="today"/);
assert.match(html, /data-view-panel="workspace"/);
assert.match(html, /data-view-panel="spaces"/);
assert.match(html, /data-view-panel="how"/);
assert.match(html, /data-view-panel="everything"/);
assert.match(html, /id="everythingJumpNav"/);
assert.match(html, /id="everythingContent"/);
assert.match(html, /id="weatherTemperature"/);
assert.match(html, /id="statsGrid"/);
assert.match(html, /<div id="spotifyFrame" aria-label="Spotify provider player"><\/div>/);
assert.match(html, /class="secondary-button doc-entry-link" href="\/doc\/"/);
assert.match(html, /class="doc-topbar-link" href="\/doc\/"/);
assert.match(html, /class="primary-button doc-cta-button" href="\/doc\/"/);
assert.doesNotMatch(html, /terminal|command line|brief-system/i);
assert.equal((html.match(/href="\/doc\/"/g) || []).length, 3, 'The briefing should expose three clear paths to the product overview.');
assert.equal((html.match(/<iframe\b/g) || []).length, 0, 'Spotify should be created by its official controller or the tap-to-play fallback.');
assert.equal((html.match(/<script src=/g) || []).length, 5, 'The briefing should load data, experience, media, app and explainer scripts.');
assert.equal((html.match(/<link rel="stylesheet"/g) || []).length, 4, 'The briefing should load core, explainer, experience and Doc-link stylesheets.');
assert.ok(html.indexOf('brief-demo-experience.js') < html.indexOf('brief-demo-app.js'), 'Experience configuration must extend navigation before the app initializes.');

assert.doesNotMatch(stagingHtml, /http-equiv="refresh"/i);
assert.match(stagingHtml, /id="entryScenarioGrid"/);
assert.match(stagingHtml, /data-view-panel="everything"/);
assert.match(stagingHtml, /\/assets\/brief\/brief-demo-app\.js/);
assert.equal(stagingHtml, html, 'The staging route should render the same standalone briefing interface as /brief/.');

assert.doesNotThrow(() => new Function(dataJs));
assert.doesNotThrow(() => new Function(experienceJs));
assert.doesNotThrow(() => new Function(mediaJs));
assert.doesNotThrow(() => new Function(appJs));
assert.doesNotThrow(() => new Function(explainersJs));
assert.doesNotThrow(() => new Function(docJs));

const context = { window: {} };
vm.createContext(context);
vm.runInContext(dataJs, context);
const data = context.window.BRIEF_DEMO_DATA;
assert.ok(data);
assert.deepEqual(Object.keys(data.scenarios), ['personal', 'relationship', 'business', 'trainer', 'team']);
for (const scenario of Object.values(data.scenarios)) {
  assert.ok(scenario.weather.hourly.length >= 4, `${scenario.id} should include useful weather movement.`);
  assert.equal(scenario.stats.length, 4, `${scenario.id} should include four compact stats.`);
  assert.ok(scenario.tabs.length >= 5, `${scenario.id} should include selective workspace navigation.`);
  assert.ok(scenario.soundtrack.spotifyTrackId, `${scenario.id} should include one Spotify provider track.`);
  assert.ok(scenario.space.private.length >= 3);
  assert.ok(scenario.space.shared.length >= 3);
}

assert.match(appJs, /const THEME_STORAGE_KEY = 'personal_os_brief_theme_v2'/);
assert.match(appJs, /function readInitialTheme\(/);
assert.match(appJs, /return storedTheme === 'dark' \? 'dark' : 'light'/);
assert.match(appJs, /return 'light'/);
assert.match(appJs, /document\.documentElement\.dataset\.theme = initialTheme/);
assert.match(appJs, /theme: initialTheme/);
assert.match(appJs, /state\.theme = theme === 'dark' \? 'dark' : 'light'/);
assert.match(appJs, /localStorage\.setItem\(THEME_STORAGE_KEY, state\.theme\)/);
assert.match(appJs, /localStorage\.removeItem\('briefNextTheme'\)/);
assert.doesNotMatch(appJs, /localStorage\.getItem\('briefNextTheme'\)/);
assert.match(appJs, /new CustomEvent\('briefdemo:scenariochange'/);
assert.match(appJs, /function selectView\(/);
assert.match(appJs, /function setScenario\(/);
assert.match(appJs, /function setWorkspaceTab\(/);
assert.match(appJs, /function moveWorkspaceTab\(/);
assert.match(appJs, /requestEntryPlayback\(selected, \$\('#entrySoundtrack'\)\?\.checked === true\)/);
assert.match(appJs, /\$\('#entrySoundtrack'\)\.checked = true/);
assert.match(appJs, /queueMicrotask\(\(\) => \$\('\[data-entry-scenario\]'\)\?\.focus/);
assert.doesNotMatch(appJs, /setTimeout|setInterval/);
assert.doesNotMatch(appJs, /terminal|command line/i);

assert.match(experienceJs, /data\.navigation\.push\(\{ id: 'everything', label: 'Everything' \}\)/);
assert.match(experienceJs, /FAMILIAR LAYOUT, FLEXIBLE CONTENT/);
assert.match(experienceJs, /Read only the approved sources needed for this update/);
assert.match(experienceJs, /The layout can adapt and still feel familiar/);
assert.match(experienceJs, /Wake up with music and a short overview/);
assert.match(experienceJs, /The operating picture at a glance/);
assert.match(experienceJs, /briefdemo:scenariochange/);
assert.doesNotMatch(experienceJs, /Personalized does not mean unpredictable/);
assert.doesNotMatch(experienceJs, /approved APIs, MCP tools/);
assert.doesNotMatch(experienceJs, /setTimeout|setInterval/);

assert.match(mediaJs, /SPOTIFY_IFRAME_API_SRC = 'https:\/\/open\.spotify\.com\/embed\/iframe-api\/v1'/);
assert.match(mediaJs, /const API_TIMEOUT_MS = 4000/);
assert.match(mediaJs, /window\.onSpotifyIframeApiReady = IFrameAPI =>/);
assert.match(mediaJs, /IFrameAPI\.createController\(/);
assert.match(mediaJs, /state\.controller\.play\(\)/);
assert.match(mediaJs, /function requestEntryPlayback\(/);
assert.match(mediaJs, /button\.disabled = false/);
assert.match(mediaJs, /Spotify is preparing in the background\. The Brief opened without waiting\./);
assert.match(mediaJs, /function setDrawerInert\(/);
assert.match(mediaJs, /drawer\.inert = isInert/);
assert.match(mediaJs, /button\.hidden = state\.fallbackMode/);
assert.match(mediaJs, /queueMicrotask\(setSoundtrackDefaultOff\)/);
assert.match(mediaJs, /document\.createElement\('iframe'\)/);
assert.match(mediaJs, /Spotify is ready in direct tap mode/);
assert.doesNotMatch(mediaJs, /event\.stopImmediatePropagation\(\)/);
assert.doesNotMatch(mediaJs, /queueMicrotask\(open\)/);
assert.doesNotMatch(mediaJs, /Loading Spotify player\.\.\.|Preparing [^'`\n]*\.\.\./);

assert.match(explainersJs, /const memoryExamples = \{/);
assert.match(explainersJs, /const spaceExamples = \{/);
assert.match(explainersJs, /family: \{/);
assert.match(explainersJs, /People appear only when they belong to an approved Space/);
assert.match(explainersJs, /role="tabpanel"/);
assert.match(explainersJs, /aria-controls="memoryComparison"/);
assert.match(explainersJs, /ArrowLeft/);
assert.match(explainersJs, /choice\.checked = false/);
assert.match(explainersJs, /scrollIntoView\(\{ block: 'nearest', inline: 'nearest' \}\)/);
assert.match(explainersJs, /PRIVATE FIRST/);
assert.doesNotMatch(explainersJs, /This is not a social friends list/);
assert.doesNotMatch(explainersJs, /setTimeout|setInterval/);

assert.match(docJs, /const plainCopy = new Map/);
assert.match(docJs, /\['A strong demonstration with a clear path to the real platform\.', 'What works now and what still needs building\.'\]/);
assert.match(docJs, /A matching `\/brief-next\/` route used for testing/);
assert.match(docJs, /applyPlainCopy\(\)/);

assert.match(css, /\.weather-card/);
assert.match(css, /\.stats-grid/);
assert.match(css, /\.primary-nav/);
assert.match(css, /\.mobile-nav/);
assert.match(css, /prefers-reduced-motion/);
assert.match(explainerCss, /\.memory-comparison/);
assert.match(explainerCss, /font-size: clamp\(1\.5rem, 6\.8vw, 2rem\)/);
assert.match(explainerCss, /font-size: clamp\(1\.75rem, 7\.8vw, 2\.2rem\)/);
assert.match(experienceCss, /--bg: #05070b/);
assert.match(experienceCss, /\.everything-jump-nav/);
assert.match(experienceCss, /\.everything-content/);
assert.match(experienceCss, /grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/);
assert.match(docLinksCss, /\.doc-topbar-link/);
assert.match(docLinksCss, /\.doc-cta-card/);
assert.match(docLinksCss, /body\s*\{[\s\S]*overflow-x: clip/);
assert.match(docLinksCss, /\.intelligence-explainers\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
assert.match(docLinksCss, /\.foundation-map\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
assert.match(docLinksCss, /\.comparison-card,[\s\S]*overflow-wrap: anywhere/);
assert.match(docLinksCss, /@media \(max-width: 620px\)/);

const route = routes.routes.find(item => item.path === '/brief/');
assert.ok(route, '/brief/ must be registered.');
assert.equal(route.visibility, 'Direct-link-only');
assert.equal(route.status, 'Active');
assert.equal(route.gated, false);

const stagingRoute = routes.routes.find(item => item.path === '/brief-next/');
assert.ok(stagingRoute, '/brief-next/ staging copy must remain registered.');
assert.equal(stagingRoute.status, 'Experimental');
assert.equal(stagingRoute.visibility, 'Direct-link-only');
assert.equal(stagingRoute.gated, false);

console.log('Brief static smoke test passed.');