const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');

const html = read('spaces/index.html');
const legacyHtml = read('brief/index.html');
const rollbackHtml = read('brief-next/index.html');
const redirectJs = read('assets/spaces-legacy-redirect.js');
const css = read('assets/brief/brief-demo.css');
const experienceCss = read('assets/brief/brief-demo-experience.css');
const docLinksCss = read('assets/brief/brief-demo-doc-links.css');
const topbarPolishCss = read('assets/brief/brief-demo-topbar-polish.css');
const advancedCss = read('assets/brief/brief-demo-advanced.css');
const conversationCss = read('assets/brief/brief-demo-conversation.css');
const advancedJs = read('assets/brief/brief-demo-advanced.js');
const conversationJs = read('assets/brief/brief-demo-conversation.js');
const appJs = read('assets/brief/brief-demo-app.js');
const mediaJs = read('assets/brief/brief-demo-media.js');
const spacesRuntimeJs = read('assets/brief/brief-spaces-runtime.js');
const docJs = read('assets/personal-os-doc.js');
const docMobileCss = read('assets/personal-os-doc-mobile-fixes.css');
const routes = JSON.parse(read('assets/cmx-routes.json'));

assert.match(html, /<html lang="en" data-theme="light">/);
assert.match(html, /<title>Spaces Demo<\/title>/);
assert.match(html, /<meta name="theme-color" content="#edf3f8"/);
assert.match(html, /noindex, nofollow/);
assert.match(html, /canonical" href="https:\/\/db\.cmxchat\.com\/spaces\/"/);
assert.match(html, /id="entryScenarioGrid" role="group" aria-label="Demo Spaces"/);
assert.doesNotMatch(html, /id="entrySoundtrack"|type="checkbox"/);
assert.match(html, /id="entryTipCarousel"/);
assert.match(html, /Wake up ready for tomorrow/);
assert.match(html, /id="entrySpacePreview"[^>]*data-entry-preview="personal"/);
assert.match(html, /id="openDemoLabel">Open Personal Briefing/);
assert.match(html, /<summary><i aria-hidden="true"><\/i>Demo data<\/summary>/);
assert.match(html, /id="themeButton"[^>]*aria-label="Switch to dark theme"[^>]*aria-pressed="false"/);
assert.match(html, /id="mobileNav"/);
assert.match(html, /id="mediaDrawer"/);
assert.match(html, /id="mediaStatus" aria-live="polite"/);
assert.match(html, /id="spotifyFrame" role="region" aria-label="Spotify provider player"/);
assert.match(html, /Shared calendars:/);
assert.match(html, /Adaptive alarm:/);
assert.match(html, /<strong>Voice:<\/strong>/);
assert.doesNotMatch(html, /class="doc-topbar-link" href="\/doc\/"/);
assert.match(html, /class="secondary-button doc-entry-link" href="\/doc\/"/);
assert.match(html, /class="primary-button doc-cta-button" href="\/doc\/"/);
assert.match(html, /brief-demo-app\.js\?v=20260808-7/);
assert.match(html, /brief-demo-media\.js\?v=20260807-4/);
assert.match(html, /brief-demo-doc-links\.css\?v=20260808-1/);
assert.match(html, /brief-demo-topbar-polish\.css\?v=20260807-3/);
assert.match(html, /brief-demo-advanced\.css\?v=20260808-1/);
assert.match(html, /brief-demo-advanced\.js\?v=20260808-1/);
assert.match(html, /brief-demo-conversation\.css\?v=20260808-11/);
assert.match(html, /brief-demo-conversation\.js\?v=20260808-1/);
assert.match(html, /brief-spaces-runtime\.js\?v=20260806-1/);
assert.match(html, /Open a briefing for the part of life you’re in/);
assert.match(html, /data-entry-choice-made="false"/);
assert.match(html, /Tap one to continue/);
assert.match(html, /Shared details meet in that Space, while private details stay with their owner/);
assert.match(html, /Hear something that fits your taste and the moment/);
assert.doesNotMatch(html, /Loading Spotify player\.\.\.|Preparing Spotify[^<]*\.\.\./);
assert.doesNotMatch(html, /id="profileSelect"|id="musicOnEntry"|id="readOnEntry"|id="enterBrief"/);

assert.match(legacyHtml, /<title>Spaces has moved<\/title>/);
assert.match(legacyHtml, /canonical" href="https:\/\/db\.cmxchat\.com\/spaces\/"/);
assert.match(legacyHtml, /http-equiv="refresh" content="1; url=\/spaces\/"/);
assert.match(legacyHtml, /spaces-legacy-redirect\.js\?v=20260806-1/);
assert.match(legacyHtml, /href="\/spaces\/"/);
assert.match(redirectJs, /target\.search = window\.location\.search/);
assert.match(redirectJs, /target\.hash = window\.location\.hash/);
assert.match(redirectJs, /window\.location\.replace\(target\.href\)/);
assert.doesNotMatch(rollbackHtml, /http-equiv="refresh"/i);
assert.match(rollbackHtml, /<title>Spaces Brief Demo<\/title>/);

for (const source of [redirectJs, appJs, mediaJs, advancedJs, conversationJs, spacesRuntimeJs, docJs]) {
  assert.doesNotThrow(() => new Function(source));
}

assert.match(appJs, /const THEME_STORAGE_KEY = 'personal_os_brief_theme_v2'/);
assert.match(appJs, /function readInitialTheme\(/);
assert.match(appJs, /return storedTheme === 'dark' \? 'dark' : 'light'/);
assert.match(appJs, /document\.documentElement\.dataset\.theme = initialTheme/);
assert.match(appJs, /function moveWorkspaceTab\(/);
assert.match(appJs, /function updateWorkspaceTabNavigation\(/);
assert.match(appJs, /function moveWorkspaceTabs\(/);
assert.match(appJs, /Continue to \$\{escapeHtml\(next\.label\)\}/);
assert.match(appJs, /data-workspace-continue/);
assert.match(appJs, /function scrollThroughToday\(/);
assert.match(appJs, /ArrowLeft/);
assert.match(appJs, /button\.tabIndex = active \? 0 : -1/);
assert.match(appJs, /<button class="entry-option" type="button" data-entry-scenario=/);
assert.match(appJs, /function renderEntryPreview\(/);
assert.match(appJs, /entrySelection: data\.meta\.defaultScenario/);
assert.match(appJs, /Open \$\{selected\.label\} Briefing/);
assert.doesNotMatch(appJs, /role="listitem"/);
assert.match(appJs, /<time>\$\{escapeHtml\(hour\.time\)\}<\/time>/);

assert.match(spacesRuntimeJs, /const productName = 'Spaces'/);
assert.match(spacesRuntimeJs, /updateObject\(window\.BRIEF_DEMO_DATA\)/);
assert.match(spacesRuntimeJs, /MutationObserver/);

assert.match(mediaJs, /const API_TIMEOUT_MS = 4000/);
assert.match(mediaJs, /const TRACK_SETTLE_DELAY_MS = 350/);
assert.doesNotMatch(mediaJs, /pendingEntryPlayback|entrySoundtrack|requestEntryPlayback/);
assert.match(mediaJs, /function setDrawerInert\(/);
assert.match(mediaJs, /state\.controller\.play\(\)/);
assert.match(mediaJs, /Spotify needs one direct tap on this device/);
assert.match(mediaJs, /Spotify is ready in direct tap mode/);
assert.match(mediaJs, /Prepare Spotify while the entry screen is visible/);
assert.doesNotMatch(mediaJs, /event\.stopImmediatePropagation\(\)/);
assert.doesNotMatch(mediaJs, /queueMicrotask\(open\)/);

assert.match(css, /:root\s*\{[\s\S]*--bg: #edf3f8/);
assert.match(css, /html\[data-theme="dark"\]/);
assert.match(css, /\.mobile-nav/);
assert.match(css, /safe-area-inset/);
assert.match(css, /@media \(max-width:/);
assert.match(css, /prefers-reduced-motion/);
assert.match(experienceCss, /\.everything-content/);
assert.match(experienceCss, /overflow-x/);
assert.match(docLinksCss, /brief-demo-topbar-polish\.css\?v=20260807-3/);
assert.match(docLinksCss, /\.media-drawer \{[\s\S]*display: block/);
assert.match(docLinksCss, /body\s*\{[\s\S]*overflow-x: clip/);
assert.match(docLinksCss, /@media \(max-width: 620px\)/);
assert.match(topbarPolishCss, /\.doc-topbar-link\s*\{[\s\S]*display: none !important/);
assert.match(topbarPolishCss, /#themeButton\s*\{[\s\S]*background: color-mix/);
assert.match(topbarPolishCss, /#themeButton > span\s*\{[\s\S]*text-shadow/);
assert.match(topbarPolishCss, /html\[data-theme="dark"\] #themeButton/);
assert.match(topbarPolishCss, /html\[data-theme="dark"\] \.topbar-context select/);
assert.match(topbarPolishCss, /-webkit-text-fill-color: #f7fbff/);
assert.match(topbarPolishCss, /color-scheme: dark/);
assert.match(topbarPolishCss, /safe-area-inset-top/);
assert.match(advancedCss, /@media \(max-width: 620px\)/);
assert.match(advancedCss, /\.financial-sheet-scroll\s*\{[\s\S]*overflow-x: auto/);
assert.match(advancedCss, /\.sheet-category-column/);
assert.match(conversationCss, /\.entry-tip-track/);
assert.match(conversationCss, /entry-tip-copy-in/);
assert.match(conversationCss, /\.spaces-ai-dialog/);
assert.match(conversationCss, /\.space-discovery-track/);
assert.match(conversationCss, /\.spaces-demo-notice/);
assert.match(conversationCss, /\.entry-space-preview/);
assert.match(conversationCss, /data-entry-choice-made="true"/);
assert.match(conversationCss, /\.entry-option \.entry-option-topline/);
assert.match(conversationCss, /grid-template-columns: repeat\(8, minmax\(0, 1fr\)\)/);
assert.match(conversationCss, /\.entry-space-preview \{\s*display: none;/);
assert.match(conversationCss, /Phones favor readable type and natural vertical flow/);
assert.match(conversationCss, /font-size: clamp\(0\.64rem, 2\.7vw, 0\.7rem\)/);
assert.match(conversationJs, /function openConversation\(/);
assert.match(appJs, /function confirmEntryChoice\(selected, trigger\)/);
assert.match(appJs, /function keepEntryChoiceVisible\(trigger\)/);
assert.match(conversationJs, /Conversation context prepared/);
assert.match(conversationJs, /briefdemo:backendrequired/);
assert.match(conversationJs, /touchstart/);
assert.match(conversationJs, /touchend/);
assert.match(conversationJs, /\}, 4200\)/);

assert.match(docJs, /personal-os-doc-mobile-fixes\.css/);
assert.match(docJs, /spacesMobileFixes/);
assert.match(docJs, /Spaces \| Shared Briefings and Context-Driven Workspace/);
assert.match(docJs, /Planned Memory & Data settings/);
assert.doesNotMatch(docJs, /const plainCopy = new Map/);
assert.match(docMobileCss, /\.final-cta \{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
assert.match(docMobileCss, /overflow-wrap: anywhere/);
assert.match(docMobileCss, /@media \(max-width: 680px\)/);
assert.match(docMobileCss, /html \{\s*font-size: 17px/);
assert.match(docJs, /personal-os-doc-mobile-fixes\.css\?v=20260808-1/);

const activeRoute = routes.routes.find(item => item.path === '/spaces/');
assert.ok(activeRoute, '/spaces/ must be registered.');
assert.equal(activeRoute.name, 'Spaces Demo');
assert.equal(activeRoute.gated, false);
assert.equal(activeRoute.status, 'Active');

const legacyRoute = routes.routes.find(item => item.path === '/brief/');
assert.ok(legacyRoute, '/brief/ compatibility route must remain registered.');
assert.equal(legacyRoute.status, 'Legacy');
assert.equal(legacyRoute.gated, false);

const rollbackRoute = routes.routes.find(item => item.path === '/brief-next/');
assert.ok(rollbackRoute, '/brief-next/ rollback snapshot must remain registered.');
assert.equal(rollbackRoute.status, 'Experimental');

console.log('Spaces device, route, soundtrack, accessibility, and light-theme smoke test passed.');
