const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');

const html = read('brief/index.html');
const stagingHtml = read('brief-next/index.html');
const css = read('assets/brief/brief-demo.css');
const experienceCss = read('assets/brief/brief-demo-experience.css');
const docLinksCss = read('assets/brief/brief-demo-doc-links.css');
const topbarPolishCss = read('assets/brief/brief-demo-topbar-polish.css');
const appJs = read('assets/brief/brief-demo-app.js');
const mediaJs = read('assets/brief/brief-demo-media.js');
const docJs = read('assets/personal-os-doc.js');
const docMobileCss = read('assets/personal-os-doc-mobile-fixes.css');
const routes = JSON.parse(read('assets/cmx-routes.json'));

assert.match(html, /<html lang="en" data-theme="light">/);
assert.match(html, /<meta name="theme-color" content="#edf3f8"/);
assert.match(html, /noindex, nofollow/);
assert.match(html, /id="entryScenarioGrid"/);
assert.match(html, /id="entrySoundtrack" type="checkbox" checked/);
assert.match(html, /id="openDemo"[^>]*disabled/);
assert.match(html, /id="themeButton"[^>]*aria-label="Switch to dark theme"[^>]*aria-pressed="false"/);
assert.match(html, /id="mobileNav"/);
assert.match(html, /id="mediaDrawer"/);
assert.doesNotMatch(html, /class="doc-topbar-link" href="\/doc\/"/);
assert.match(html, /class="secondary-button doc-entry-link" href="\/doc\/"/);
assert.match(html, /class="primary-button doc-cta-button" href="\/doc\/"/);
assert.match(html, /brief-demo-app\.js/);
assert.match(html, /brief-demo-media\.js\?v=20260806-1/);
assert.match(html, /brief-demo-doc-links\.css\?v=20260806-1/);
assert.match(html, /Choose a briefing to explore/);
assert.match(html, /Play the soundtrack when the demo opens/);
assert.doesNotMatch(html, /Loading Spotify player\.\.\.|Preparing Spotify[^<]*\.\.\./);
assert.doesNotMatch(html, /id="profileSelect"|id="musicOnEntry"|id="readOnEntry"|id="enterBrief"/);
assert.doesNotMatch(html, /brief-config\.js/);
assert.equal(stagingHtml, html, 'The staging and production Brief routes should use the same current interface.');

assert.doesNotThrow(() => new Function(appJs));
assert.doesNotThrow(() => new Function(mediaJs));
assert.match(appJs, /const THEME_STORAGE_KEY = 'personal_os_brief_theme_v2'/);
assert.match(appJs, /function readInitialTheme\(/);
assert.match(appJs, /return storedTheme === 'dark' \? 'dark' : 'light'/);
assert.match(appJs, /return 'light'/);
assert.match(appJs, /document\.documentElement\.dataset\.theme = initialTheme/);
assert.match(appJs, /localStorage\.removeItem\('briefNextTheme'\)/);
assert.match(appJs, /localStorage\.setItem\(THEME_STORAGE_KEY, state\.theme\)/);
assert.match(appJs, /function moveWorkspaceTab\(/);
assert.match(appJs, /ArrowLeft/);
assert.match(appJs, /button\.tabIndex = active \? 0 : -1/);
assert.match(appJs, /queueMicrotask\(\(\) => \$\('\[data-entry-scenario\]'\)\?\.focus/);
assert.doesNotMatch(appJs, /localStorage\.getItem\('briefNextTheme'\)/);

assert.match(mediaJs, /const API_TIMEOUT_MS = 4000/);
assert.match(mediaJs, /const TRACK_SETTLE_DELAY_MS = 350/);
assert.match(mediaJs, /pendingEntryPlayback/);
assert.match(mediaJs, /function syncEntryButton\(/);
assert.match(mediaJs, /button\.disabled = false/);
assert.match(mediaJs, /function setDrawerInert\(/);
assert.match(mediaJs, /drawer\.inert = isInert/);
assert.match(mediaJs, /button\.hidden = state\.fallbackMode/);
assert.match(mediaJs, /state\.controller\.play\(\)/);
assert.match(mediaJs, /function playPendingEntryRequest\(/);
assert.match(mediaJs, /function enableSoundtrackForScenarioChoice\(/);
assert.match(mediaJs, /document\.addEventListener\('pointerdown'/);
assert.match(mediaJs, /setScenario\(window\.BRIEF_DEMO_DATA\?\.meta\?\.defaultScenario/);
assert.match(mediaJs, /Spotify needs one direct tap on this device/);
assert.match(mediaJs, /Spotify is ready in direct tap mode/);
assert.match(mediaJs, /Prepare Spotify while the entry screen is visible/);
assert.match(mediaJs, /installSpotifyApi\(\);\s*\}\)\(\);/);
assert.match(mediaJs, /isEntryReady: \(\) => true/);
assert.doesNotMatch(mediaJs, /event\.stopImmediatePropagation\(\)/);
assert.doesNotMatch(mediaJs, /queueMicrotask\(open\)/);

assert.match(css, /:root\s*\{[\s\S]*--bg: #edf3f8/);
assert.match(css, /html\[data-theme="dark"\]/);
assert.match(css, /\.mobile-nav/);
assert.match(css, /safe-area-inset/);
assert.match(css, /@media \(max-width:/);
assert.match(css, /prefers-reduced-motion/);
assert.match(experienceCss, /\.everything-content/);
assert.match(experienceCss, /overflow-x/);
assert.match(docLinksCss, /brief-demo-topbar-polish\.css\?v=20260806-1/);
assert.match(docLinksCss, /html\[data-theme="light"\] \.alarm-section/);
assert.match(docLinksCss, /html\[data-theme="light"\] \.full-privacy/);
assert.match(docLinksCss, /html\[data-theme="light"\] \.alarm-section \.alarm-flow article/);
assert.match(docLinksCss, /html\[data-theme="dark"\] \.alarm-section/);
assert.match(docLinksCss, /html\[data-theme="dark"\] \.full-privacy/);
assert.match(docLinksCss, /\.media-drawer \{[\s\S]*display: block/);
assert.match(docLinksCss, /body\[data-entered="false"\] #mediaDrawer/);
assert.match(docLinksCss, /\.media-drawer\.is-open \.media-sheet/);
assert.match(docLinksCss, /body\s*\{[\s\S]*overflow-x: clip/);
assert.match(docLinksCss, /\.intelligence-explainers\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
assert.match(docLinksCss, /\.foundation-map\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
assert.match(docLinksCss, /\.foundation-node,[\s\S]*min-height: 0/);
assert.match(docLinksCss, /\.mobile-nav button[\s\S]*overflow-wrap: anywhere/);
assert.match(topbarPolishCss, /\.doc-topbar-link\s*\{[\s\S]*display: none !important/);
assert.match(topbarPolishCss, /#themeButton\s*\{[\s\S]*linear-gradient/);
assert.match(topbarPolishCss, /html\[data-theme="dark"\] #themeButton/);
assert.match(topbarPolishCss, /padding-top: max\(10px, env\(safe-area-inset-top\)\)/);

assert.match(docJs, /personal-os-doc-mobile-fixes\.css/);
assert.match(docJs, /personalOsMobileFixes/);
assert.match(docJs, /const plainCopy = new Map/);
assert.match(docJs, /applyPlainCopy\(\)/);
assert.match(docMobileCss, /\.final-cta \{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
assert.match(docMobileCss, /\.final-cta > \*/);
assert.match(docMobileCss, /overflow-wrap: anywhere/);
assert.match(docMobileCss, /@media \(max-width: 680px\)/);

const route = routes.routes.find(item => item.path === '/brief/');
assert.ok(route, '/brief/ must remain registered.');
assert.equal(route.gated, false);
assert.equal(route.status, 'Active');

console.log('Current Brief device, topbar, soundtrack, and light-theme smoke test passed.');