const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');

const html = read('spaces/index.html');
const legacyHtml = read('brief/index.html');
const rollbackHtml = read('brief-next/index.html');
const redirectJs = read('assets/spaces-legacy-redirect.js');
const css = read('assets/brief/brief-demo.css');
const explainerCss = read('assets/brief/brief-demo-explainers.css');
const experienceCss = read('assets/brief/brief-demo-experience.css');
const docLinksCss = read('assets/brief/brief-demo-doc-links.css');
const topbarPolishCss = read('assets/brief/brief-demo-topbar-polish.css');
const advancedCss = read('assets/brief/brief-demo-advanced.css');
const conversationCss = read('assets/brief/brief-demo-conversation.css');
const docEditorialCss = read('assets/personal-os-doc-editorial.css');
const dataJs = read('assets/brief/brief-demo-data.js');
const advancedJs = read('assets/brief/brief-demo-advanced.js');
const conversationJs = read('assets/brief/brief-demo-conversation.js');
const spacesRuntimeJs = read('assets/brief/brief-spaces-runtime.js');
const experienceJs = read('assets/brief/brief-demo-experience.js');
const mediaJs = read('assets/brief/brief-demo-media.js');
const appJs = read('assets/brief/brief-demo-app.js');
const explainersJs = read('assets/brief/brief-demo-explainers.js');
const docJs = read('assets/personal-os-doc.js');
const routes = JSON.parse(read('assets/cmx-routes.json'));

assert.match(html, /<html lang="en" data-theme="light">/);
assert.match(html, /<title>Spaces Demo<\/title>/);
assert.match(html, /A working demo of Spaces/);
assert.match(html, /<meta name="theme-color" content="#edf3f8"/i);
assert.match(html, /<meta name="robots" content="noindex, nofollow/);
assert.match(html, /<link rel="canonical" href="https:\/\/db\.cmxchat\.com\/spaces\/"/);
assert.match(html, /script-src 'self' https:\/\/open\.spotify\.com/);
assert.match(html, /connect-src https:\/\/open\.spotify\.com/);
assert.match(html, /id="entryScenarioGrid" role="group" aria-label="Demo Spaces"/);
assert.match(html, /Choose the Space you want to open/);
assert.doesNotMatch(html, /id="entrySoundtrack"|type="checkbox"/);
assert.match(html, /id="entryTipCarousel"/);
assert.match(html, /Ask from the section in front of you/);
assert.match(html, /Hear something that fits your taste and the moment/);
assert.doesNotMatch(html, /readOnEntry|read aloud/i);
assert.doesNotMatch(html, /Loading Spotify player\.\.\.|Preparing Spotify[^<]*\.\.\./);
assert.match(html, /data-view-panel="today"/);
assert.match(html, /data-view-panel="workspace"/);
assert.match(html, /data-view-panel="spaces"/);
assert.match(html, /data-view-panel="how"/);
assert.match(html, /data-view-panel="everything"/);
assert.match(html, /id="everythingJumpNav"/);
assert.match(html, /id="everythingContent"/);
assert.match(html, /id="weatherTemperature"/);
assert.match(html, /id="statsGrid"/);
assert.match(html, /<div id="spotifyFrame" role="region" aria-label="Spotify provider player"><\/div>/);
assert.match(html, /id="mediaStatus" aria-live="polite"/);
assert.match(html, /Shared calendars:/);
assert.match(html, /Adaptive alarm:/);
assert.match(html, /<strong>Voice:<\/strong>/);
assert.match(html, /class="secondary-button doc-entry-link" href="\/doc\/"/);
assert.doesNotMatch(html, /class="doc-topbar-link" href="\/doc\/"/);
assert.match(html, /class="primary-button doc-cta-button" href="\/doc\/"/);
assert.match(html, /brief-demo-explainers\.css\?v=20260807-3/);
assert.match(html, /brief-demo-experience\.css\?v=20260807-2/);
assert.match(html, /brief-demo-doc-links\.css\?v=20260807-3/);
assert.match(html, /brief-demo-topbar-polish\.css\?v=20260807-3/);
assert.match(html, /brief-demo-advanced\.css\?v=20260807-2/);
assert.match(html, /brief-demo-conversation\.css\?v=20260808-1/);
assert.match(html, /brief-spaces-runtime\.js\?v=20260806-1/);
assert.match(html, /brief-demo-data\.js\?v=20260807-5/);
assert.match(html, /brief-demo-advanced\.js\?v=20260807-3/);
assert.match(html, /brief-demo-experience\.js\?v=20260807-5/);
assert.match(html, /brief-demo-media\.js\?v=20260807-4/);
assert.match(html, /brief-demo-app\.js\?v=20260807-6/);
assert.match(html, /brief-demo-explainers\.js\?v=20260807-4/);
assert.match(html, /brief-demo-conversation\.js\?v=20260807-4/);
assert.doesNotMatch(html, /terminal|command line|brief-system/i);
assert.equal((html.match(/href="\/doc\/"/g) || []).length, 2, 'Documentation should remain available at entry and inside How it works, not in the live header.');
assert.equal((html.match(/<iframe\b/g) || []).length, 0, 'Spotify should be created by its official controller or the tap-to-play fallback.');
assert.equal((html.match(/<script src=/g) || []).length, 8, 'Spaces should load data, advanced modules, branding, experience, media, app, explainers and conversation scripts.');
assert.equal((html.match(/<link rel="stylesheet"/g) || []).length, 7, 'Spaces should load core, explainer, experience, Doc-link, topbar, advanced and conversation stylesheets.');
assert.ok(html.indexOf('brief-demo-data.js') < html.indexOf('brief-spaces-runtime.js'), 'Spaces branding must load after the data source.');
assert.ok(html.indexOf('brief-demo-data.js') < html.indexOf('brief-demo-advanced.js'), 'Advanced modules must load after their data source.');
assert.ok(html.indexOf('brief-spaces-runtime.js') < html.indexOf('brief-demo-experience.js'), 'Spaces branding must update the data before the experience initializes.');

assert.match(legacyHtml, /<title>Spaces has moved<\/title>/);
assert.match(legacyHtml, /http-equiv="refresh" content="1; url=\/spaces\/"/);
assert.match(legacyHtml, /spaces-legacy-redirect\.js\?v=20260806-1/);
assert.match(legacyHtml, /href="\/spaces\/"/);
assert.doesNotMatch(legacyHtml, /id="entryScenarioGrid"/);
assert.doesNotThrow(() => new Function(redirectJs));
assert.match(redirectJs, /window\.location\.replace\(target\.href\)/);

assert.doesNotMatch(rollbackHtml, /http-equiv="refresh"/i);
assert.match(rollbackHtml, /<title>Spaces Brief Demo<\/title>/);
assert.match(rollbackHtml, /canonical" href="https:\/\/db\.cmxchat\.com\/brief\/"/);
assert.match(rollbackHtml, /id="entryScenarioGrid"/);
assert.notEqual(rollbackHtml, html, 'The rollback snapshot is intentionally separate from the active `/spaces/` route.');

for (const source of [dataJs, advancedJs, conversationJs, spacesRuntimeJs, experienceJs, mediaJs, appJs, explainersJs, docJs]) {
  assert.doesNotThrow(() => new Function(source));
}

const context = { window: {} };
vm.createContext(context);
vm.runInContext(dataJs, context);
const data = context.window.BRIEF_DEMO_DATA;
assert.ok(data);
assert.deepEqual(Object.keys(data.scenarios), ['personal', 'relationship', 'family', 'business', 'accounting', 'trainer', 'team']);
for (const scenario of Object.values(data.scenarios)) {
  assert.ok(scenario.weather.hourly.length >= 4, `${scenario.id} should include useful weather movement.`);
  assert.equal(scenario.stats.length, 4, `${scenario.id} should include four compact stats.`);
  assert.ok(scenario.tabs.length >= 5, `${scenario.id} should include selective workspace navigation.`);
  assert.ok(scenario.soundtrack.spotifyTrackId, `${scenario.id} should include one Spotify provider track.`);
  assert.equal(scenario.soundtrack.alternates.length, 2, `${scenario.id} should include two alternate soundtracks.`);
  assert.ok(scenario.priority?.targetTab, `${scenario.id} should include a priority target.`);
  assert.equal(scenario.checkIn?.choices.length, 3, `${scenario.id} should include three quick answers.`);
  assert.equal(scenario.highlights?.length, 3, `${scenario.id} should include three focused module links.`);
  assert.ok(scenario.space.private.length >= 3);
  assert.ok(scenario.space.shared.length >= 3);
}
assert.equal(data.scenarios.personal.details.habits.layout, 'habits');
assert.equal(data.scenarios.personal.details.habits.habits[0].best, '16-day record');
assert.equal(data.scenarios.family.details.calendar.layout, 'calendar');
assert.equal(data.scenarios.family.details.chores.layout, 'board');
assert.equal(data.scenarios.family.details.shopping.layout, 'checklist');
assert.ok(data.scenarios.family.details.calendar.days.some(day => day.events.some(event => event.kind === 'Availability only')));
assert.equal(data.scenarios.business.details.executive.layout, 'partner-operations');
assert.equal(data.scenarios.business.details.projects.projects.length, 4);
assert.equal(data.scenarios.business.details.calendar.days.find(day => day.highlighted)?.day, 'Tuesday');
assert.equal(data.scenarios.accounting.label, 'Accountant and client');
assert.equal(data.scenarios.accounting.details.cash.rows.length, 8);
assert.equal(data.scenarios.accounting.details.portfolio.assets.length, 4);

assert.match(spacesRuntimeJs, /const legacyName = 'Personal OS'/);
assert.match(spacesRuntimeJs, /const productName = 'Spaces'/);
assert.match(spacesRuntimeJs, /updateObject\(window\.BRIEF_DEMO_DATA\)/);
assert.match(spacesRuntimeJs, /MutationObserver/);

assert.match(appJs, /const THEME_STORAGE_KEY = 'personal_os_brief_theme_v2'/);
assert.match(appJs, /function readInitialTheme\(/);
assert.match(appJs, /return storedTheme === 'dark' \? 'dark' : 'light'/);
assert.match(appJs, /document\.documentElement\.dataset\.theme = initialTheme/);
assert.match(appJs, /new CustomEvent\('briefdemo:scenariochange'/);
assert.match(appJs, /function selectView\(/);
assert.match(appJs, /function setScenario\(/);
assert.match(appJs, /function setWorkspaceTab\(/);
assert.match(appJs, /function renderHabitTracker\(/);
assert.match(appJs, /function renderFamilyCalendar\(/);
assert.match(appJs, /function renderHouseholdBoard\(/);
assert.match(appJs, /function renderShoppingList\(/);
assert.match(appJs, /BRIEF_DEMO_ADVANCED\?\.renderDetail/);
assert.match(appJs, /function renderPriority\(/);
assert.match(appJs, /function renderHighlights\(/);
assert.match(appJs, /function saveBriefUpdate\(/);
assert.match(appJs, /function keepDocumentAligned\(/);
assert.doesNotMatch(appJs, /entrySoundtrack|requestEntryPlayback/);
assert.match(appJs, /<button class="entry-option" type="button" data-entry-scenario=/);
assert.doesNotMatch(appJs, /role="listitem"/);
assert.match(appJs, /<time>\$\{escapeHtml\(hour\.time\)\}<\/time>/);
assert.doesNotMatch(appJs, /setInterval/);

assert.match(experienceJs, /data\.navigation\.push\(\{ id: 'everything', label: 'Everything' \}\)/);
assert.match(experienceJs, /ADAPTIVE BRIEF/);
assert.match(experienceJs, /Read only the approved sources needed for this update/);
assert.match(experienceJs, /The layout stays familiar as the briefing changes/);
assert.match(experienceJs, /Start the morning with music and a short overview/);
assert.match(experienceJs, /class="weather-card full-weather-card"/);
assert.doesNotMatch(experienceJs, /business:\s*\{/);
assert.match(experienceJs, /briefdemo:scenariochange/);
assert.doesNotMatch(experienceJs, /Personalized does not mean unpredictable/);
assert.doesNotMatch(experienceJs, /approved APIs, MCP tools/);
assert.doesNotMatch(experienceJs, /setInterval/);

assert.match(topbarPolishCss, /\.explainer-tabs button\[aria-selected="true"\]/);
assert.match(topbarPolishCss, /-webkit-text-fill-color: #ffffff/);
assert.match(topbarPolishCss, /overscroll-behavior-inline: contain/);

assert.match(mediaJs, /SPOTIFY_IFRAME_API_SRC = 'https:\/\/open\.spotify\.com\/embed\/iframe-api\/v1'/);
assert.match(mediaJs, /const API_TIMEOUT_MS = 4000/);
assert.match(mediaJs, /window\.onSpotifyIframeApiReady = IFrameAPI =>/);
assert.match(mediaJs, /IFrameAPI\.createController\(/);
assert.match(mediaJs, /state\.controller\.play\(\)/);
assert.doesNotMatch(mediaJs, /requestEntryPlayback|pendingEntryPlayback|entrySoundtrack/);
assert.match(mediaJs, /function renderTrackChoices\(/);
assert.match(mediaJs, /function selectTrack\(/);
assert.match(mediaJs, /function setDrawerInert\(/);
assert.match(mediaJs, /drawer\.inert = isInert/);
assert.match(mediaJs, /Prepare Spotify while the entry screen is visible/);
assert.match(mediaJs, /document\.createElement\('iframe'\)/);
assert.doesNotMatch(mediaJs, /event\.stopImmediatePropagation\(\)/);
assert.doesNotMatch(mediaJs, /Loading Spotify player\.\.\.|Preparing [^'`\n]*\.\.\./);

assert.match(explainersJs, /const memoryExamples = \{/);
assert.match(explainersJs, /const spaceExamples = \{/);
assert.match(explainersJs, /People appear only when they belong to an approved Space/);
assert.match(explainersJs, /role="tabpanel"/);
assert.match(explainersJs, /aria-controls="memoryComparison"/);
assert.match(explainersJs, /ArrowLeft/);
assert.match(explainersJs, /PRIVATE FIRST/);
assert.match(explainersJs, /Accountant \+ client/);
assert.doesNotMatch(explainersJs, /This is not a social friends list/);

assert.match(docJs, /Spaces \| Context-Driven Workspace and Daily Brief/);
assert.match(docJs, /A Space learns from connected accounts, direct input, and corrections/);
assert.match(docJs, /Planned Memory & Data settings/);
assert.match(docJs, /Cloudflare could become infrastructure beneath Spaces/);
assert.match(docJs, /spaces_doc_theme_v1/);
assert.doesNotMatch(docJs, /const plainCopy = new Map/);

assert.match(css, /\.weather-card/);
assert.match(css, /\.stats-grid/);
assert.match(css, /\.primary-nav/);
assert.match(css, /\.mobile-nav/);
assert.match(css, /prefers-reduced-motion/);
assert.match(explainerCss, /\.memory-comparison/);
assert.match(experienceCss, /--bg: #05070b/);
assert.match(experienceCss, /\.everything-jump-nav/);
assert.match(docLinksCss, /brief-demo-topbar-polish\.css\?v=20260807-3/);
assert.match(docLinksCss, /body\s*\{[\s\S]*overflow-x: clip/);
assert.match(docLinksCss, /@media \(max-width: 620px\)/);
assert.match(topbarPolishCss, /\.doc-topbar-link\s*\{[\s\S]*display: none !important/);
assert.match(topbarPolishCss, /html\[data-theme="dark"\] \.topbar-context select/);
assert.match(topbarPolishCss, /color-scheme: dark/);
assert.match(topbarPolishCss, /-webkit-text-fill-color: #f7fbff/);
assert.match(topbarPolishCss, /safe-area-inset-top/);
assert.match(topbarPolishCss, /#themeButton > span/);
assert.match(advancedCss, /\.partner-operations/);
assert.match(advancedCss, /\.financial-sheet-scroll/);
assert.match(advancedCss, /\.track-choices/);
assert.match(advancedJs, /function renderPartnerCalendar\(/);
assert.match(advancedJs, /function renderSpreadsheet\(/);
assert.match(advancedJs, /function renderPortfolio\(/);
assert.match(advancedJs, /sheet-category-column/);
assert.match(conversationCss, /\.entry-tip-track/);
assert.match(conversationCss, /entry-tip-copy-in/);
assert.match(conversationCss, /\.spaces-ai-dialog/);
assert.match(conversationCss, /\.space-discovery-track/);
assert.match(conversationJs, /function openConversation\(/);
assert.match(conversationJs, /Conversation context prepared/);
assert.match(docEditorialCss, /\.boundary-center > small\s*\{[\s\S]*color: #617286/);
assert.match(docEditorialCss, /\.memory-index\s*\{[\s\S]*color: #10253a/);

const activeRoute = routes.routes.find(item => item.path === '/spaces/');
assert.ok(activeRoute, '/spaces/ must be registered.');
assert.equal(activeRoute.name, 'Spaces Demo');
assert.equal(activeRoute.visibility, 'Direct-link-only');
assert.equal(activeRoute.status, 'Active');
assert.equal(activeRoute.gated, false);

const legacyRoute = routes.routes.find(item => item.path === '/brief/');
assert.ok(legacyRoute, '/brief/ compatibility route must remain registered.');
assert.equal(legacyRoute.status, 'Legacy');
assert.equal(legacyRoute.visibility, 'Legacy');
assert.equal(legacyRoute.gated, false);

const rollbackRoute = routes.routes.find(item => item.path === '/brief-next/');
assert.ok(rollbackRoute, '/brief-next/ rollback snapshot must remain registered.');
assert.equal(rollbackRoute.name, 'Spaces Brief Rollback Snapshot');
assert.equal(rollbackRoute.status, 'Experimental');
assert.equal(rollbackRoute.visibility, 'Direct-link-only');
assert.equal(rollbackRoute.gated, false);

console.log('Spaces active, legacy redirect, and rollback static smoke test passed.');
