"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = process.cwd();
const html = fs.readFileSync(path.join(root, "checkin/index.html"), "utf8");
const js = fs.readFileSync(path.join(root, "assets/checkin/checkin.js"), "utf8");
const css = fs.readFileSync(path.join(root, "assets/checkin/checkin.css"), "utf8");
const phase1Css = fs.readFileSync(path.join(root, "assets/checkin/checkin-phase1-controls.css"), "utf8");
const refineJs = fs.readFileSync(path.join(root, "assets/checkin/checkin-refine.js"), "utf8");
const contractJs = fs.readFileSync(path.join(root, "assets/checkin/checkin-status-contract.js"), "utf8");
const { normalize } = require(path.join(root, "assets/checkin/checkin-status-contract.js"));

const validStatus = normalize({ interval_hours: 72, grace_hours: 24, document_count: 0, contact_count: 0, organization_count: 0, update_revision_count: 0, trigger_action_count: 1 });
assert.deepEqual(validStatus, { schemaCompatible: true, intervalHours: 72, graceHours: 24, documentCount: 0, contactCount: 0, organizationCount: 0, updateRevisionCount: 0, actionCount: 1 });

const configurableStatus = normalize({ interval_hours: 24, grace_hours: 6 });
assert.deepEqual(configurableStatus, { schemaCompatible: true, intervalHours: 24, graceHours: 6, documentCount: 0, contactCount: 0, organizationCount: 0, updateRevisionCount: 0, actionCount: 0 });

const missingCountsStatus = normalize({ interval_hours: 72, grace_hours: 24, document_count: "stale" });
assert.equal(missingCountsStatus.schemaCompatible, true, "valid timing must not be suppressed by missing/stale aggregate counts");
assert.equal(missingCountsStatus.documentCount, 0);
assert.equal(missingCountsStatus.actionCount, 0);

const invalidTiming = normalize({ interval_hours: 0, grace_hours: 721, trigger_action_count: 1 });
assert.equal(invalidTiming.schemaCompatible, false);
assert.equal(invalidTiming.intervalHours, 72);
assert.equal(invalidTiming.graceHours, 24);
assert.doesNotMatch(Object.values(invalidTiming).join(" "), /undefined|null|NaN/);

assert.match(html, /Primary 72 hour switch/);
assert.match(html, /new 72 hour window/);
assert.match(html, /Operator key/);
assert.doesNotMatch(html, /authEmail|authPassword|Sign in to Check In/);
assert.match(html, /data-view-panel="records"/);
assert.match(html, /DOCUMENT STORAGE/);
assert.match(html, /Protected uploads unavailable/);
assert.match(html, /CONTACTS/);
assert.match(html, /ORGANIZATIONS/);
assert.match(html, /PRIVATE FIELD NOTEBOOK/);
assert.match(html, /Insert update/);
assert.match(html, /REVISION HISTORY/);
assert.match(html, /PROTECTED CONTINGENCY PLAN/);
assert.match(html, /DATABASE AUDIT LOG/);
assert.match(html, /Review state sequence/);
assert.match(html, /72 hour operating window/);
assert.match(html, /id="documentPublicCount"/);
assert.match(html, /id="contactPublicCount"/);
assert.match(html, /id="organizationPublicCount"/);
assert.match(html, /id="updatePublicCount"/);
assert.match(html, /id="actionPublicCount"/);
assert.match(html, /Private contents require operator authorization|PROTECTED RECORDS/);
assert.match(html, /id="lockNowButton"/);
assert.match(html, /id="operatorSessionStrip"/);
assert.match(html, /id="sessionStripCountdown"/);
assert.match(html, /id="receiptDialog"/);
assert.match(html, /Proof of life recorded/);
assert.match(html, /contenteditable="true"/);
assert.match(html, /data-command="undo"/);
assert.match(html, /data-command="redo"/);
assert.match(html, /data-command="bold"/);
assert.match(html, /data-command="italic"/);
assert.match(html, /data-command="underline"/);
assert.match(html, /data-command="strikeThrough"/);
assert.match(html, /data-block="h1"/);
assert.match(html, /data-command="insertUnorderedList"/);
assert.match(html, /data-command="insertOrderedList"/);
assert.match(html, /data-block="blockquote"/);
assert.match(html, /data-insert="link"/);
assert.match(html, /id="saveState"/);
assert.match(html, /id="wordCount"/);
assert.match(html, /id="revisionPanel"/);
assert.match(html, /id="focusMode"/);
assert.match(html, /id="mobileSettings"/);
assert.match(html, /id="mobileNavSettings"/);
assert.match(html, /data-view="timeline"/);
assert.doesNotMatch(html, /id="intervalSelect"|id="graceSelect"|Save changes/);
assert.match(html, /id="publicActionSequence"/);
assert.match(html, /connect-src 'self' https:\/\/api\.cmxchat\.com/);

assert.match(js, /\/checkin\/public\/status/);
assert.match(js, /credentials: "include"/);
assert.match(js, /X-CSRF-Token/);
assert.match(js, /document_uploads_enabled/);
assert.match(contractJs, /document_count/);
assert.match(contractJs, /contact_count/);
assert.match(contractJs, /organization_count/);
assert.match(contractJs, /update_revision_count/);
assert.match(contractJs, /trigger_action_count/);
assert.match(contractJs, /schemaCompatible: intervalValid && graceValid/);
assert.match(js, /renderLockedInventory/);
assert.match(js, /session\.expires_at/);
assert.match(js, /clearPrivateState/);
assert.match(js, /els\.lockNowButton[\s\S]*addEventListener\("click", lockOperator\)/);
assert.match(js, /renderPublicActionSequence/);
assert.match(js, /state\.actionCount/);
assert.match(js, /state\.intervalHours = normalized\.intervalHours/);
assert.match(js, /state\.intervalHours \* 3600000/);
assert.match(js, /`\$\{state\.intervalHours\} hours rolling`/);
assert.match(js, /clearPrivateState/);
assert.match(js, /editorDirty/);
assert.match(js, /markdownToHtml/);
assert.match(js, /nodeToMarkdown/);
assert.match(js, /beforeunload/);
assert.match(js, /editor-focus/);
assert.match(js, /receiptDialog\.showModal/);
assert.match(js, /\$\$\("\[data-view\]"\)/);
assert.match(js, /\$\("meta\[name=theme-color\]"\)/);
assert.doesNotMatch(js, /\$\$\(\[data-/);
assert.match(js, /\/checkin\/operator\/unlock/);
assert.match(js, /\/checkin\/operator\/session/);
assert.doesNotMatch(js, /switchId|switch_id|owner_id|localStorage\.setItem\([^,]*operator/i);
assert.doesNotMatch(js, /localStorage\.setItem\([^,]*(csrf|record|markdown|action)/i);
assert.doesNotMatch(html + js, /actions will fire|will execute|delivery initiated|automatic release|\barmed\b/i);
assert.doesNotMatch(html + js, /Saturday|weekly|165 hours|168 hours|72-hour|24-hour|proof-of-life|check-in window/i);
assert.match(js, /STATUS DATA PARTIALLY AVAILABLE/);
assert.doesNotMatch(js, /\["records", "updates", "actions", "activity"\][\s\S]{0,120}requireOperator/);
const protectedLoads = ["records", "updates", "actions", "activity"].map(name => js.indexOf(`api("/checkin/operator/${name}")`));
const protectedGate = js.indexOf("async function loadProtected()");
assert.ok(protectedLoads.every(index => index > -1 && index < protectedGate));
assert.match(js.slice(protectedGate), /Promise\.all\(\[loadRecords\(\), loadRevisions\(\), loadActions\(\), loadActivity\(\)\]\)/);
assert.match(js, /detectOperator[\s\S]*operator\/session[\s\S]*loadProtected/);
assert.match(js, /Simulation stops\. No record, note, action, or deadline changed/);
assert.match(js, /THEME_KEY/);

assert.match(css, /\.record-columns/);
assert.match(css, /\.notebook/);
assert.match(css, /\.inventory-strip/);
assert.match(css, /\.locked-card/);
assert.match(css, /\.operator-only/);
assert.match(css, /\.operator-session-strip/);
assert.match(css, /\.public-action-sequence/);
assert.match(css, /\.writing-canvas/);
assert.match(css, /\.editor-focus/);
assert.match(css, /\.receipt-dialog/);
assert.match(css, /@media\(max-width:700px\)/);
assert.match(css, /@media\(max-width:680px\)/);
assert.match(css, /html\[data-theme="dark"\]/);

// Real-device regression guards from the 2026-08-17 Samsung/Chrome acceptance pass.
assert.match(phase1Css, /@media\(max-width:700px\)[\s\S]*#mobileSettings\{display:grid!important/);
assert.match(phase1Css, /#lockNowButton\{display:none!important\}/);
assert.match(phase1Css, /:has\(#phase1OverrideMeta\):not\(:has\(#phase1DeadlineOverride\)\)/);
assert.match(phase1Css, /content:"NOT ACTIVE"/);
assert.doesNotMatch(contractJs, /observe\(document\.body,\s*\{[\s\S]{0,120}subtree:\s*true/);
assert.doesNotMatch(refineJs, /observe\(document\.body,\s*\{[\s\S]{0,120}subtree:\s*true/);

console.log("Check-in operations smoke test passed.");
