const fs=require('fs');
const html=fs.readFileSync('lab/email/index.html','utf8');
const api=fs.readFileSync('assets/lab/lab-email-api-v1.js','utf8');
const app=fs.readFileSync('assets/lab/lab-email-v1.js','utf8');
const css=fs.readFileSync('assets/lab/lab-email-v1.css','utf8');
const must=(text,needle,label)=>{if(!text.includes(needle))throw new Error(`missing ${label}: ${needle}`)};
const forbid=(text,needle,label)=>{if(text.includes(needle))throw new Error(`forbidden ${label}: ${needle}`)};
must(html,'data-cmx-gate="black-prompt"','Black Prompt gate');
must(html,'data-email-lab="v1"','Email Lab marker');
must(html,'EMAIL · MANUAL ACTION PLAYGROUND','manual boundary');
must(html,'Real manual SMTP','real mode label');
must(html,'Process now · development control','development process boundary');
must(html,'No unattended authority lives here','authority truth');
must(api,'/checkin/operator/connections/${encodeURIComponent(connectionId)}/readiness','connection readiness');
must(api,'/receipt`','typed Run receipt');
must(api,'X-CSRF-Token','CSRF mutation contract');
must(api,'credentials:"include"','protected cookie');
must(app,'recipient_person_id','Person UUID');
must(app,'recipient_contact_method_id','ContactMethod UUID');
must(app,'sender_identity_id','SenderIdentity UUID');
must(app,'content_asset_id','ContentAsset UUID');
must(app,'expected_revision','optimistic draft revision');
must(app,'provider_mode:mode','typed provider mode');
must(app,'manual_owner','manual authority presentation');
must(app,'real_smtp','real SMTP mode');
must(app,'fake_behavior','fake behavior');
must(app,'crypto.randomUUID()','idempotency/step UUID generation');
must(css,'@media(max-width:760px)','mobile layout');
forbid(app,'localStorage','canonical local storage');
forbid(app,'sessionStorage','canonical session storage');
forbid(api,'smtp_password','SMTP secret');
forbid(api,'smtp_username','SMTP secret');
forbid(html,'CC</','unsupported CC control');
forbid(html,'BCC</','unsupported BCC control');
forbid(html,'attachment','unsupported attachment control');
console.log('Continuum Email Lab v1 contract: PASS');
