const fs=require('fs');
const html=fs.readFileSync('email/index.html','utf8');
const legacyRedirect=fs.readFileSync('assets/continuum-legacy-route-redirect.js','utf8');
const operatorApi=fs.readFileSync('assets/continuum-operator-api-v1.js','utf8');
const receiptLink=fs.readFileSync('assets/continuum-runtime-receipt-link-v1.js','utf8');
const api=fs.readFileSync('assets/lab/lab-email-api-v1.js','utf8');
const app=fs.readFileSync('assets/lab/lab-email-v3.js','utf8');
const workspace=fs.readFileSync('assets/lab/lab-email-workspace-v2.js','utf8');
const css=fs.readFileSync('assets/lab/lab-email-v1.css','utf8');
const backendCss=fs.readFileSync('assets/lab/lab-email-backend-v3.css','utf8');
const must=(text,needle,label)=>{if(!text.includes(needle))throw new Error(`missing ${label}: ${needle}`)};
const forbid=(text,needle,label)=>{if(text.includes(needle))throw new Error(`forbidden ${label}: ${needle}`)};

must(html,'data-cmx-gate="black-prompt"','Black Prompt gate');
must(html,'data-email-lab="v3"','Email v3 marker');
must(html,'CONTINUUM · MANUAL EMAIL','manual email boundary');
must(html,'id="backendUnlockForm"','backend unlock form');
must(html,'id="operatorKeyInput"','operator key input');
must(html,'id="backendDisconnect"','session end control');
must(html,'contenteditable="true"','rich editor');
must(html,'data-email-editor','rich editor marker');
must(html,'Safe simulation','safe simulation label');
must(html,'value="real_smtp" disabled','real SMTP disabled during acceptance');
must(html,'Process now · development control','development process boundary');
must(html,'Scope: manual owner only.','authority boundary');
must(html,'href="/requests/"','Requests navigation');
must(html,'href="/control/"','canonical Control navigation');
must(html,'href="/directory/"','canonical Directory navigation');
must(html,'href="/automations/"','canonical Automations navigation');
must(html,'href="/library/"','canonical Library navigation');
must(html,'continuum-operator-api-v1.js','shared operator transport');
must(html,'lab-email-v3.js','v3 orchestration');
must(html,'lab-email-workspace-v2.js','workspace script');
must(legacyRedirect,"['/lab/email/', '/email/']",'retired Lab Email compatibility mapping');
if(fs.existsSync('lab/email/index.html'))throw new Error('retired /lab/email/ page must not exist');

must(operatorApi,'/checkin/operator','operator API prefix');
must(operatorApi,'/unlock','operator unlock');
must(operatorApi,'operator_key','operator key request');
must(operatorApi,'X-CSRF-Token','shared CSRF contract');
must(operatorApi,'credentials: "include"','protected cookie');
must(operatorApi,'createPerson','Directory mutation adapter');
must(operatorApi,'continuum-runtime-receipt-link-v1.js','shared receipt navigation loader');
forbid(operatorApi,'localStorage','operator local storage');
forbid(operatorApi,'sessionStorage','operator session storage');

must(api,'${op}/connections/${encodeURIComponent(connectionId)}/readiness','connection readiness');
must(api,'/receipt`','typed Run receipt');
must(api,'cmx:runtime-receipt-read','receipt navigation event');
must(api,'automationId:String(automationId||"")','exact Automation ID handoff');
must(api,'runId:String(runId||"")','exact Run ID handoff');
must(api,'X-CSRF-Token','Email API CSRF mutation contract');
must(api,'credentials:"include"','Email API protected cookie');

must(receiptLink,"['/email/', '/requests/']",'Email/Requests receipt surfaces');
must(receiptLink,"url.searchParams.set('automation_id', automationId)",'Control Automation reference');
must(receiptLink,"url.searchParams.set('run_id', runId)",'Control Run reference');
must(receiptLink,'Open this Run in Control','human-readable Control link');
forbid(receiptLink,'operator_key','no operator key in receipt navigation');
forbid(receiptLink,'csrf','no CSRF in receipt navigation');
forbid(receiptLink,'subject','no message subject in receipt navigation');
forbid(receiptLink,'body','no message body in receipt navigation');

must(app,'operator.session({ refresh: true })','existing protected session check');
must(app,'operator.unlock(key)','backend unlock');
must(app,'operator.logout()','backend session end');
must(app,'not_deployed','deployment-gap classification');
must(app,'recipient_person_id','Person UUID');
must(app,'recipient_contact_method_id','ContactMethod UUID');
must(app,'sender_identity_id','SenderIdentity UUID');
must(app,'content_asset_id','ContentAsset UUID');
must(app,'expected_revision','optimistic draft revision');
must(app,'provider_mode: "fake"','safe simulation provider mode');
must(app,'manual_owner','manual authority presentation');
must(app,'real_smtp','real SMTP boundary');
must(app,'fake_behavior','fake behavior');
must(app,'crypto.randomUUID()','idempotency/step UUID generation');
must(app,'No external email was sent','simulation side-effect language');

must(workspace,'sanitizeHtml','rich editor sanitization');
must(workspace,'plainTextFromHtml','backend-safe text projection');
must(workspace,'document.execCommand','rich editor commands');
must(workspace,'source.value = plain','rich editor backend projection');
must(workspace,'MutationObserver','freeze-state lock');
must(workspace,'data-email-mode','write/preview modes');

must(css,'--bg:#f5f7fa','neutral light surface');
must(css,'--blue:#1674c5','Continuum blue accent');
must(css,'html[data-theme="dark"]','dark theme');
must(css,'@media(max-width:760px)','mobile layout');
must(backendCss,'.backend-access','backend access UI');
must(backendCss,'data-state="not_deployed"','deployment state styling');

forbid(app,'localStorage','canonical local storage');
forbid(app,'sessionStorage','canonical session storage');
forbid(workspace,'localStorage','private-content local storage');
forbid(workspace,'sessionStorage','private-content session storage');
forbid(api,'smtp_password','SMTP secret');
forbid(api,'smtp_username','SMTP secret');
forbid(html,'id="cc','unsupported CC control');
forbid(html,'id="bcc','unsupported BCC control');
forbid(html,'type="file"','unsupported attachment control');

console.log('Continuum Email v3 protected backend + rich composer + Control receipt navigation contract: PASS');
