const fs=require('fs');
const html=fs.readFileSync('requests/index.html','utf8');
const app=fs.readFileSync('assets/requests/requests-v1.js','utf8');
const api=fs.readFileSync('assets/continuum-operator-api-v1.js','utf8');
const css=fs.readFileSync('assets/requests/requests-v1.css','utf8')+fs.readFileSync('assets/requests/requests-v2.css','utf8');
const routes=JSON.parse(fs.readFileSync('assets/cmx-routes.json','utf8'));
const roadmap=fs.readFileSync('docs/continuum-frontend-roadmap-CURRENT.md','utf8');
const handoff=fs.readFileSync('docs/continuum-requests-CURRENT.md','utf8');
const must=(text,needle,label)=>{if(!text.includes(needle))throw new Error(`missing ${label}: ${needle}`)};
const forbid=(text,needle,label)=>{if(text.includes(needle))throw new Error(`forbidden ${label}: ${needle}`)};

must(html,'data-cmx-gate="black-prompt"','protected page gate');
must(html,'data-requests-version="v2"','Requests v2 marker');
must(html,'CONTINUUM · OPERATOR DOORWAY','operator doorway boundary');
must(html,'id="backendUnlockForm"','unlock form');
must(html,'id="requestInput"','batch input');
must(html,'id="parseRequest"','contact preview action');
must(html,'id="approveRequest"','contact approval action');
must(html,'id="modeEmail"','Email mode');
must(html,'id="emailFrom"','Email sender input');
must(html,'id="emailTo"','Email recipient input');
must(html,'id="previewEmailRequest"','Email preview action');
must(html,'id="approveEmailRequest"','Email approval action');
must(html,'Safe simulation only.','safe simulation boundary');
must(html,'no external email is sent','external side-effect boundary');
must(html,'not a direct database console','database boundary');
must(html,'not a second Email engine','single execution path');
must(html,'href="/email/"','Email navigation');
must(html,'href="/directory/"','Directory navigation');
must(html,'continuum-operator-api-v1.js','shared operator API');

must(api,'operator_key','operator unlock request');
must(api,'X-CSRF-Token','CSRF contract');
must(api,'createPerson','Person create adapter');
must(api,'createContact','ContactMethod create adapter');
must(api,'listConnections','Connection read adapter');
must(api,'connectionReadiness','readiness adapter');
must(api,'createContent','Library adapter');
must(api,'createAutomation','Automation adapter');
must(api,'requestRun','Runtime adapter');
must(api,'processRun','development process adapter');
must(api,'getReceipt','receipt adapter');
forbid(api,'localStorage','operator local storage');
forbid(api,'sessionStorage','operator session storage');

must(app,'api.session({ refresh: true })','session check');
must(app,'api.unlock(key)','protected unlock');
must(app,'api.createPerson({ display_name: row.name })','Person mutation');
must(app,'api.createContact(person.id','ContactMethod mutation');
must(app,'duplicate email in this batch','batch duplicate protection');
must(app,'findRecipient','recipient resolver');
must(app,'findSender','sender resolver');
must(app,'Preview is read-only','Email read-only preview text');
must(app,'api.createContent({ kind: "text"','Email Library flow');
must(app,'api.updateAutomationDraft','Email Automation Draft flow');
must(app,'provider_mode: "fake"','fake-only Runtime mode');
must(app,'api.getReceipt','typed receipt read');
must(app,'No external email was sent','side-effect truth');
must(app,'No automatic retry was attempted','retry safety');
must(app,'row.status = "partial"','partial durable result');
must(app,'Directory create API is not deployed','deployment-gap truth');
forbid(app,'fetch(','direct transport bypass');
forbid(app,'localStorage','canonical local storage');
forbid(app,'sessionStorage','canonical session storage');
forbid(app,'WebSocket','unapproved execution transport');
forbid(app,'real_smtp','real SMTP forbidden in Requests v2');

must(css,'.workspace','Requests workspace');
must(css,'.preview-wrap','review table');
must(css,'.request-modes','request modes');
must(css,'.email-grid','Email request layout');
must(css,'.receipt-view','receipt layout');
must(css,'@media(max-width:640px)','mobile layout');

if(!routes.routes.some(route=>route.path==='/requests/'&&route.gated===true))throw new Error('Requests route must be registered and gated');
if(routes.version<38)throw new Error('route registry version must include Requests graduation');

must(roadmap,'Phase F2 — `/requests/` operator doorway','approved Requests roadmap');
must(roadmap,'One backend, many interfaces.','architecture principle');
must(handoff,'Preview-before-write invariant','Requests contact handoff');
must(handoff,'Email preview is read-only','Requests Email preview contract');
must(handoff,'Approve & run safe simulation','Requests Email execution contract');
must(handoff,'No external email is sent','safe provider boundary');
must(handoff,'direct PostgreSQL console','database boundary');

console.log('Continuum Requests v2 contacts + Email safe-simulation contract: PASS');
